//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
            this.ProductGemstones = new HashSet<ProductGemstones>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public int metal_id { get; set; }
        public int size_id { get; set; }
        public float price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGemstones> ProductGemstones { get; set; }
        public virtual ProductMetals ProductMetals { get; set; }
        public virtual ProductSizes ProductSizes { get; set; }
    }
}
